scrape_configs:
  - job_name: 'grafana_monitoring'
    static_configs:
      - targets: ['prometheus:9090']
  - job_name: 'AiApp local Server'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets:
          - 'host.docker.internal:24000'
          - 'host.docker.internal:22022'
          - 'host.docker.internal:12000'
          - 'host.docker.internal:12001'
          - 'host.docker.internal:20101'
          - 'host.docker.internal:22000'
